plugins/config/repository.yaml
Similar to https://github.com/ignition-tooling/gzdev/pull/21/
Part of:
* https://github.com/ignition-tooling/release-tools/issues/360
* https://github.com/ignition-tooling/release-tools/issues/361
* https://github.com/ignition-tooling/release-tools/issues/362
=> Nightlies on Edifice: more libraries

plugins/config/repository.yaml
This will help with testing the Heightmap pull request
Signed-off-by: Steven Peters <scpeters@openrobotics.org>
=> Use prereleases for ignition-gazebo5

plugins/config/repository.yaml
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/847 and https://github.com/ignitionrobotics/ign-gazebo/pull/869
=> ign-gazebo3: use prerelease for now

plugins/config/repository.yaml
Part of https://github.com/ignition-tooling/release-tools/issues/545
=> Nightlies for garden dependents of ign-rendering

plugins/config/repository.yaml
Part of https://github.com/ignition-tooling/release-tools/issues/554
=> Use nightlies for ign-fuel-tools8

plugins/config/repository.yaml
Part of https://github.com/ignition-tooling/release-tools/issues/554
=> Use nightlies in ign-transport12

plugins/config/repository.yaml
Needed by https://github.com/ignitionrobotics/sdformat/pull/747
=> Use nightlies for sdformat13

plugins/config/repository.yaml
This should have been done as part of https://github.com/ignition-tooling/release-tools/issues/554, but it was only needed now that we're tackling https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden: ci_matching_branch/bump_garden_ign-msgs9

plugins/config/repository.yaml
See https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden: ign-common5

plugins/config/repository.yaml
See https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden: ign-physics6

plugins/config/repository.yaml
* Part of https://github.com/ignition-tooling/release-tools/issues/574 and https://github.com/ignition-tooling/release-tools/issues/545
* Needed by https://github.com/ignitionrobotics/ign-rendering/pull/525
=> Bumps in garden: ci_matching_branch/bump_garden_ign-rendering7

plugins/config/repository.yaml
* Fixing https://github.com/ignition-tooling/gzdev/pull/47
* Part of ignition-tooling/release-tools#574
Spelling is hard
=> Fix physics spelling

.github/workflows/main.yml, gzdev.py, plugins/ign-docker-env.py, plugins/repository.py, plugins/repository_TEST.py
Should pass everything except documentation checks.
=> Lint to flake8 standards

plugins/config/repository.yaml
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Needed by: https://github.com/ignitionrobotics/ign-gazebo/pull/1333.
=> Enable preleases on ign-gazebo6

README.md
- Support for renaming ign to gz names (#57)
- Update new GitHub org
=> Update to new GitHub org

plugins/config/repository.yaml
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
=> Enable nightlies for new main branches

plugins/config/repository.yaml
Garden has prereleases for all the packages now.
=> Use prereleases for Garden

.github/workflows/main.yml, plugins/config/repository.yaml
Needed by https://github.com/gazebosim/gz-harmonic/pull/1
=> Use nightlies for gz-harmonic

plugins/config/repository.yaml
Part of https://github.com/gazebo-tooling/release-tools/issues/974
=> Use stable repos for gz-msgs10

plugins/config/repository.yaml
Part of https://github.com/gazebo-tooling/release-tools/issues/1027
=> Use nightlies for Ionic branches

plugins/repository.py
Add a parameter to set the keyserver to use by the `apt-key` . Related to https://github.com/gazebo-tooling/release-tools/issues/1069
=> Implement keyserver parameter option

plugins/repository.py
Fixed a bug introduced in #79 .
Tested [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_cmake-ci-ign-cmake2-focal-amd64&build=34)](https://build.osrfoundation.org/job/gz_cmake-ci-ign-cmake2-focal-amd64/34/)
=> Added gpg_check positional argument

plugins/config/repository.yaml
https://github.com/gazebo-tooling/release-tools/issues/1092
=> Enable nightlies for main branches
