- .travis.yml
- README.md
- gzdev.py
- plugins/config/_test_repository.yaml
- plugins/config/repository.yaml
- plugins/repository.py
- plugins/repository_TEST.py
- requirements.txt
Usage can be found in the [README file](https://github.com/osrf/gzdev/blob/e142b472eaec895b7ced7fe538f106fff04d72b7/README.md)
Some pending features:
* Add expire clause to configuration file in order to install prerelease/nightly repository only during a given period of time
* Avoid to install the repository key twice is the project is using two repositories with the same key
* Add ROS repositories to the configuration file
* Implemente the `list` and `disable`actions
> Add repository plugin: enable/disable/list repositories

- plugins/config/repository.yaml
cc @j-rivero 
needed by https://bitbucket.org/osrf/gazebo/pull-requests/3161/require-ign-msgs5-51-and-use-ignition-msgs/diff
> gazebo11: use prereleases

- plugins/config/repository.yaml
This should fix https://github.com/ignition-tooling/release-tools/issues/240 and help to keep CI working for the rest of libraries that expect to find sdformat10, which is in the prerelease repository. (i.e.: https://github.com/ignitionrobotics/ign-gazebo/pull/244)
> Use prerelease + nightly repositories in new Dome libraries

- requirements.txt
This indirectly should fix focal support on those system that does not have distro installed.
> Add distro to requirements.txt

- plugins/config/repository.yaml
https://github.com/ignitionrobotics/ign-physics/pull/86 needs prerelease version of sdformat 9.3.0. Revert this after stable release of sdformat 9.3.0.
> ignition-physics2: use prerelease for now

- .travis.yml
- plugins/config/repository.yaml
https://github.com/osrf/gazebo/pull/2824 needs prerelease version of sdformat 9.3.0. Revert this after stable release of sdformat 9.3.0.
This also adds a CI test for yaml syntax to fix #17. There is a syntax error in 410d0e6, CI fails after adding the check, and yaml syntax is then fixed in 4726492.
> gazebo11: use prerelease for now

- plugins/config/repository.yaml
Use nightlies for `ignition-edifice` to fix https://build.osrfoundation.org/job/ignition_edifice-install-pkg-focal-amd64/6/
Also use nightlies for `ign-rendering5` and its dependencies, see https://github.com/ignition-tooling/release-tools/issues/331.
> Use nightlies for Edifice versions

- .github/workflows/main.yml
- README.md
- plugins/ign-docker-env.py
Here's a proposal that breaks out `--volume` into a separate argument for `ign-docker-env`, as discussed [here](https://github.com/ignition-tooling/gzdev/pull/23#discussion_r536191384).
To pass in a single volume:
```
gzdev ign-docker-env citadel --vol /foo:/bar
```
To pass in multiple volumes, separate volumes with `::`:
```
gzdev ign-docker-env citadel --vol /foo:/bar::/ws:/baz
```
You can add on `--rocker-args` as a separate argument:
```
gzdev ign-docker-env citadel --vol /foo:/bar --rocker-args '--dev-helpers'
```
> made --volume a separate argument

- plugins/config/repository.yaml
osrf/sdformat#434 needs ignition-math 6.8.0~pre1
cc @brawner
> sdformat11: use prereleases for now

- plugins/config/repository.yaml
We have pre-releases of all Edifice libraries, so we don't need to use the pre-release repos anymore.
> Remove nightlies for Edifice

- plugins/config/repository.yaml
Part of https://github.com/ignition-tooling/release-tools/issues/428.
Some of these are not strictly necessary yet, some of them may never be necessary. Nevertheless, I find it easier to have a rule that we apply to all main branches rather than having to analyze case by case. It shouldn't hurt that `ign-cmake3` loads nightlies even though it doesn't use (for now) anything from there.
I propose the following workflow:
1. Beginning of development cycle: all main branches use nightlies
1. Feature freeze: as pre-releases start to be made, swap `nightly` for `prerelease`
1. Code freeze: after stable releases are made, bump all main branches to the next versions and go back to 1. :point_up: 
---
Reverted the idea above for now, so this PR has only the branches that are known to go into …
> Use nightlies on all main branches

- plugins/ign-docker-env.py
- requirements.txt
requires https://github.com/adlarkin/ign-rocker/pull/2 (@j-rivero, I wasn't able to request you as a reviewer for this PR, but if you want to try it before I merge, let me know if you see any issues. I have tested it, and it seems to work fine)
I've added fortress support to `ign-docker-env` and have also added some error checking to make sure that users pass in a valid argument for the ignition version.
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
> add fortress support to ign-docker-env

- plugins/config/repository.yaml
Reverting #33. Testing the https://github.com/ignitionrobotics/ign-physics/pull/277 pre-release with https://github.com/ignitionrobotics/ign-gazebo/pull/661 worked well and we're ready for a stable release in https://github.com/ignitionrobotics/ign-physics/pull/279.
> Revert pre-releases for gazebo5

- plugins/config/repository.yaml
Removed nightlies from all libs above `ign-gazebo`, and appended it for the ones below
https://github.com/ignition-tooling/release-tools/issues/459
> Use pre-releases for Fortress

- plugins/config/repository.yaml
ign-physics 2.5 has been released, so revert ign-gazebo to stable.
> Revert ign-gazebo3 prerelease

- plugins/config/repository.yaml
This is not strictly necessary now, but it's future-proofing in case we bump any of `ign-math`'s dependencies
See https://github.com/ignition-tooling/release-tools/issues/574
> Bumps in garden: ign-math7

- plugins/config/repository.yaml
Revisiting an idea which was originally introduced in https://github.com/ignition-tooling/gzdev/pull/31, but eventually reverted.
* Current approach: use nightlies when a `main` branch is known to go into the upcoming collection
* Cons:
* It's one more PR to open as part of a dependency bumping process, which is already complicated as it is
* We often refrain from adding the nighlies for a `main` branch while bumping if we know that it won't be immediately necessary. This means we need to track it back when it is necessary, causing more churn. See https://github.com/ignition-tooling/gzdev/pull/31
* Pros:
* Only use nightlies when strictly necessary, so if we see nightlies enabled, we know they're needed
* Suggestion: use nightlies for all `main` branches
* Cons:
* We lose the nuance of …
> Use nightlies for all main branches

- plugins/repository.py
`distro` recently updated to 1.7.0, which changed how some of the APIs work.
First, `linux_distribution()` is deprecated, and it is now returning the codename differently
```
In [5]: distro.__version__                                                                                                                 
Out[5]: '1.7.0'
In [6]: distro.linux_distribution()                                                                                                        
<ipython-input-6-ac24b2663c5c>:1: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
distro.linux_distribution()
Out[6]: ('Ubuntu', '20.04', 'Focal Fossa') …
```
> Adjust usage of distro for new API

- plugins/ign-docker-env.py
Since Dome and Edifice are now EOL, we should not allow users to pick one of these Ignition versions when using the `ign-docker-env` tool.
Signed-off-by: Ashton Larkin <42042756+adlarkin@users.noreply.github.com>
> Remove EOL Dome and Edifice from ign-docker-env tool

- plugins/config/repository.yaml
Reverting #55 now that https://github.com/ignitionrobotics/ign-gazebo/pull/1333 is merged.
CC @nkoenig
> Disable prereleases on ign-gazebo6

- plugins/config/repository.yaml
Add duplicate entries for ignition packages to support the rename of them to gazebo.
> Support for renaming ign to gz names

- plugins/config/repository.yaml
For gz-sim and gz-launch, I'm keeping nightlies so we don't have to wait for some prereleases to be built.
> Use prereleases for Harmonic branches

- plugins/config/repository.yaml
This updates gz-rendering8 to use the prerelease repos so we can test the new version of libogre-next-2.3 that was just released (see https://github.com/gazebosim/gz-sim/issues/920#issuecomment-1716429220)
> Use prerelease in gz-rendering8

- .github/workflows/main.yml
- plugins/config/_test_repository.yaml
- plugins/config/repository.yaml
- plugins/repository.py
Second take of #74. Reproducing the text here:
As the `apt-key` man pages recommends, this PR  removes the use of it and replaces it with a `Signed-By` clause that points to a download gpg key.
The PR adds the `key_url` field to yaml to store the URI to grab the key from. The `key`field is still preserve to check that the key stored has the expected fringerprint to improve the security. 
The tool will replace:
* Automatically the files under `/etc/apt/config.d/sources.list.d/_gzdev_` files if they exist with a new one using the `signed-by` clause.
* Previous gzdev installation of gpg keys inside `/usr/share/keyring`
The tool will not replace:
* Any key authorized before using `apt-key` or other method.
> Replace apt-key with keyring installation (take II)

- plugins/config/repository.yaml
This reverts commit 70b78ffeff9268d6cf21fa5cf0242ba8109ab5d3 since gz-msgs 10.1.0  is being released.
> Revert "Use pre-releases for gz-sim8 to test gz-msgs 10.1.0 (#77)"

- README.md
- plugins/config/_test_repository.yaml
- plugins/repository.py
- plugins/repository_TEST.py
The PR implement and document the ability to specify a platform requirement to the `--project` configuration. This requirement allow us to implement different use cases that will depend on the platform in use by gzdev, for example to use prerelease repositories in the Harmonic libs while keeping jammy in stable.
> Support platform requirements on gzdev projects

- plugins/config/repository.yaml
Add the Harmonic libraries with the requirement to run on Noble to make use of the prerelease repository.
Tested https://build.osrfoundation.org/job/_test_gz_math-ci-gz-math7-noble-amd64/11/console . Although Noble is quite broken at this moment, the log shows that the prerelease repository is being used.
> Use prerelease for Harmonic / Noble libraries

- .github/workflows/main.yml
- plugins/repository.py
Add a `--pre-clean` option that removes any existing gzdev installation from the system before proceeding with the next actions.
> Implement purge/--pre-cleanup option

- gzdev.py
- plugins/config/repository.yaml
- plugins/ign-docker-env.py
- plugins/repository.py
Enable prereleases in all Ionic branches (some `main` and some with stable ranches like `gz-cmake4`). The goal is to be able to use prereleases for the tutorial party but still keep nightlies to expedite iterating on existing PRs.
> Add prereleases Ionic branches

- .github/workflows/main.yml
- .github/workflows/pyright.yml
- plugins/config/repository.yaml
- plugins/ign-docker-env.py
This allow us to install the ROS repositories via gzdev in the same way that we install the Gazebo repositories. Added are the ros_bootstrap and the ROS 2 repositories. This last one with main and testing options.
> Support for ROS repositories in the repository module

- plugins/ign-docker-env.py
Part of https://github.com/gazebo-tooling/release-tools/issues/1223
Since Citadel is now EOL, we should update the ign-docker-env tool.
**DO NOT MERGE UNTIL Jan 1, 2025**
> Remove Citadel from ign-docker-env tool

- plugins/config/repository.yaml
Alternative to https://github.com/gazebo-tooling/gzdev/pull/94
Use ros2 repo for zenoh packages instead of the eclipse-zenoh repo
Related PR: https://github.com/gazebosim/gz-transport/pull/614
> Add ros2 repo to gz-transport15 for zenoh package
